(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ahs-idle-interval 0.5)
 '(android-mode-avd "Android8")
 '(android-mode-sdk-dir "~/Projects/wthr.cc/android/sdk")
 '(apropos-do-all t)
 '(apropos-sort-by-scores t)
 '(auto-insert-mode t)
 '(blink-cursor-mode nil)
 '(bm-highlight-style (quote bm-highlight-only-fringe))
 '(c-basic-offset 4)
 '(c-default-style
   (quote
    ((c-mode . "bsd")
     (java-mode . "java")
     (awk-mode . "awk")
     (other . "gnu"))))
 '(calendar-week-start-day 1)
 '(column-number-mode t)
 '(compilation-ask-about-save nil)
 '(compilation-read-command nil)
 '(compilation-scroll-output t)
 '(default-major-mode (quote text-mode) t)
 '(dired-listing-switches "-l --group-directories-first")
 '(echo-keystrokes 0.1)
 '(erc-autojoin-channels-alist (quote (("irc.freenide.net" "#django" "#emacs"))))
 '(erc-autojoin-mode t)
 '(erc-nick "kmmbvnr")
 '(flymake-python-pyflakes-extra-arguments (quote ("--max-line-length=120")))
 '(fringe-mode (quote (nil . 0)) nil (fringe))
 '(global-auto-revert-mode t)
 '(global-linum-mode t)
 '(hscroll-step 1)
 '(htmlize-output-type (quote font))
 '(ido-enable-flex-matching t)
 '(ido-enable-tramp-completion nil)
 '(ido-everywhere t)
 '(ido-max-dir-file-cache 150)
 '(ido-max-directory-size 100000)
 '(ido-max-work-directory-list 150)
 '(ido-max-work-file-list 50)
 '(ido-mode (quote both) nil (ido))
 '(indent-tabs-mode nil)
 '(inhibit-startup-screen t)
 '(initial-scratch-message nil)
 '(js2-mode-indent-ignore-first-tab t)
 '(mouse-avoidance-mode (quote exile) nil (avoid))
 '(nxml-child-indent 4)
 '(nxml-outline-child-indent 4)
 '(python-skeleton-autoinsert t)
 '(python-use-skeletons t)
 '(recentf-exclude
   (quote
    ("^/su:" "^/sudo:" "^/ssh:" "ido.last$" "/Servers/")))
 '(recentf-mode t)
 '(rng-nxml-auto-validate-flag nil)
 '(ruby-indent-level 4)
 '(safe-local-variable-values (quote ((compile-command . "go-runner -c main.go"))))
 '(scroll-conservatively 3)
 '(scroll-margin 5)
 '(scroll-step 1)
 '(scroll-up-aggressively nil)
 '(sgml-basic-offset 4)
 '(show-paren-mode t)
 '(tab-width 4)
 '(tabbar-mode t nil (tabbar))
 '(tabbar-use-images nil)
 '(tramp-mode nil)
 '(truncate-lines t)
 '(uniquify-buffer-name-style (quote forward) nil (uniquify))
 '(winner-mode t nil (winner)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "beige" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 101 :width normal :foundry "unknown" :family "Liberation Mono"))))
 '(ahs-face ((t (:background "Orange1" :foreground "black"))))
 '(js2-error-face ((((class color) (background light)) (:background "LightPink"))))
 '(js2-external-variable-face ((t (:background "LightBlue2"))))
 '(js2-warning-face ((((class color) (background light)) (:background "LightBlue2"))))
 '(linum ((t (:inherit (shadow default) :background "lightgrey" :foreground "black"))))
 '(show-paren-match ((t (:background "lightblue"))))
 '(tabbar-default ((t (:inherit variable-pitch :background "gray90" :foreground "black" :height 0.8))))
 '(tabbar-default-face ((t (:inherit variable-pitch :background "grey90" :foreground "white" :height 0.8))))
 '(tabbar-selected ((t (:inherit tabbar-default :background "DarkGray" :foreground "black" :box (:line-width 3 :color "DarkGray")))))
 '(tabbar-selected-face ((t (:inherit tabbar-default-face :background "DarkGray" :foreground "black" :box (:line-width 3 :color "DarkGray")))))
 '(tabbar-unselected ((t (:inherit tabbar-default :background "gray" :foreground "black" :box (:line-width 3 :color "gray")))))
 '(tabbar-unselected-face ((t (:inherit tabbar-default-face :background "gray" :foreground "black" :box (:line-width 1 :color "gray"))))))
